# Generated by Django 2.1.3 on 2020-05-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='likes_num',
            field=models.IntegerField(default=0),
        ),
    ]
