# Generated by Django 2.1.3 on 2020-05-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlepost_likes_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='remarks_num',
            field=models.IntegerField(default=0),
        ),
    ]
